# Generated by Django 3.2.20 on 2023-09-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="initial_consonant",
            field=models.CharField(default="", editable=False, max_length=30),
            preserve_default=False,
        ),
    ]
