# Generated by Django 3.2.20 on 2023-09-02 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_initial_consonant"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/barcodes"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="option_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.optiongroup",
            ),
        ),
    ]
