# Generated by Django 3.2.21 on 2023-09-16 12:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_auto_20230902_2228"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
