version: '3.9'

services:
  mysql-db:
    container_name: mysql-db
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./database/mysql:/var/lib/mysql
    env_file:
      - .env
  cafehere-was:
    container_name: cafehere-was
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn core.wsgi:application -w 4 -b 0.0.0.0:8000
    volumes:
      - ./:/app
    depends_on:
      - mysql-db
    env_file:
      - .env
    ports:
      - "8000:8000"