# Generated by Django 3.2.20 on 2023-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafes", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cafe",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"), name="unique_cafe_name_per_user"
            ),
        ),
    ]
